import bpy

class SFX_Action_Props(bpy.types.PropertyGroup):
    id :   bpy.props.IntProperty(name = 'ID',
                                 description = 'ID',
                                 default = 0)
    name : bpy.props.StringProperty(name = 'Name',
                                 description = 'Name',
                                 default = 'Name')
    saved : bpy.props.BoolProperty(name = 'Saved',
                                 description = 'Saved',
                                 default = False)
    path : bpy.props.StringProperty(name = 'Path',
                                 description = 'Path',
                                 default ='Path')
    description : bpy.props.StringProperty(name = 'Description',
                                 description = 'Describe the Charactristics of that Action',
                                 default = 'Default Description')
    signed : bpy.props.BoolProperty(name = 'Signed',
                                 description = 'Signed',
                                 default = False)
    maxAcc : bpy.props.FloatProperty(name = 'Max Acc',
                                 description = 'Max Acc',
                                 default = 0)
    maxVel : bpy.props.FloatProperty(name = 'Max Vel',
                                 description = 'Max Vel',
                                 default = 0)
    minPos : bpy.props.FloatProperty(name = 'Min Pos',
                                 description = 'Min Pos',
                                 default = 0)
    maxPos : bpy.props.FloatProperty(name = 'Max Pos',
                                 description = 'Max Pos',
                                 default = 0)
    length : bpy.props.FloatProperty(name = 'Length',
                                 description = 'Length',
                                 default = 0)
    duration : bpy.props.FloatProperty(name = 'Duration',
                                 description = 'Duration',
                                 default = 0)
    Pos_SM : bpy.props.StringProperty(name = 'Pos_SM',
                                 description = 'Pos_SM',
                                 default = '[[0,1],[0,0]]')
    Jrk : bpy.props.StringProperty(name = 'Jrk',
                                 description = 'Jrk',
                                 default = 'Jrk')
    Acc : bpy.props.StringProperty(name = 'Acc',
                                 description = 'Acc',
                                 default = 'Acc')
    Vel : bpy.props.StringProperty(name = 'Vel',
                                 description = 'Vel',
                                 default = 'Vel')
    Pos : bpy.props.StringProperty(name = 'Pos',
                                 description = 'Pos',
                                 default = 'Pos')
    VP  : bpy.props.StringProperty(name = 'VP',
                                 description = 'VP',
                                 default = 'VP')
